/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        System.out.println("Java server starting on port 9000...");
        try {
            while (true) {
                Thread.sleep(60_000);
            }
        } catch (InterruptedException e) {
            System.out.println("Server interrupted.");
        }
    }
}
